#@baseUrl = http://localhost:5000
@baseUrl = http://localhost:8080

POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "usernameOrEmail": "admin@example.com",
  "password": "password"
}

###

POST {{baseUrl}}/api/auth/logout

###

GET {{baseUrl}}/api/todolists

###

GET {{baseUrl}}/api/todolists/1

###

POST {{baseUrl}}/api/todolists
Content-Type: application/json

{
  "name": "Hobby"
}

###

DELETE {{baseUrl}}/api/todolists/1

###

GET {{baseUrl}}/api/todos

###

GET {{baseUrl}}/api/todos?todoListId=1

###

POST {{baseUrl}}/api/todos
Content-Type: application/json

{
  "text": "Buy groceries",
  "todoListId": 1
}

###

PATCH {{baseUrl}}/api/todos/reorder
Content-Type: application/json

{
  "orderedIds": [3, 1, 2]
}

###

DELETE {{baseUrl}}/api/todos/1

###

GET {{baseUrl}}/api/users/cc6aead7-855c-4410-bb4b-2067f5738528

###

POST {{baseUrl}}/api/users/avatar
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="avatar.png"
Content-Type: image/png

< ./avatar.png
--WebAppBoundary--

###
