#@baseUrl = http://localhost:5000
@baseUrl = http://localhost:8080

GET {{baseUrl}}/api/todos

###

POST {{baseUrl}}/api/todos
Content-Type: application/json

{
  "text": "Buy groceries"
}

###

DELETE {{baseUrl}}/api/todos/1

###
